# Generated by Django 2.2.9 on 2020-01-27 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date_of_issue', models.DateField(verbose_name='Data wystawienia')),
                ('invoice_nr', models.CharField(max_length=250, verbose_name='Numer faktur')),
                ('invoice_name', models.CharField(max_length=250, verbose_name='Nazwa faktury')),
                ('invoice_netto', models.FloatField(verbose_name='Kwota netto')),
                ('invoice_vat', models.FloatField(verbose_name='Vat')),
                ('invoice_brutto', models.FloatField(default=100, verbose_name='Kwota brutto')),
                ('invoice_place', models.CharField(choices=[('Żagań', 'Żagań'), ('Krasiczyn', 'Krasiczyn'), ('Kielce', 'Kielce'), ('Żory', 'Żory'), ('Nie dotyczy', 'Nie dotyczy')], default='Nie dotyczy', max_length=20, verbose_name='Miejsce którego dotyczy')),
            ],
        ),
    ]
