# Generated by Django 2.2.9 on 2020-01-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='tytuł')),
                ('content', models.TextField(verbose_name='zawartość')),
                ('published', models.DateTimeField(verbose_name='data publikacji')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date_of_issue', models.DateField()),
                ('invoice_nr', models.CharField(max_length=250)),
                ('invoice_name', models.CharField(max_length=250)),
                ('invoice_netto', models.FloatField()),
                ('invoice_vat', models.FloatField()),
                ('invoice_brutto', models.FloatField(default=100)),
                ('invoice_place', models.CharField(choices=[('Żagań', 'Żagań'), ('Krasiczyn', 'Krasiczyn'), ('Kielce', 'Kielce'), ('Żory', 'Żory'), ('Nie dotyczy', 'Nie dotyczy')], default='Nie dotyczy', max_length=6)),
                ('invoice_file', models.FileField(upload_to='')),
            ],
        ),
    ]
