# Generated by Django 2.2.7 on 2020-01-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='tytuł')),
                ('content', models.TextField(verbose_name='zawartość')),
                ('published', models.DateTimeField(verbose_name='data publikacji')),
            ],
        ),
    ]
