# Generated by Django 2.2.9 on 2020-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_file',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_brutto',
            field=models.FloatField(default=100, verbose_name='Kwota brutto'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date_of_issue',
            field=models.DateField(verbose_name='Data wystawienia'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(max_length=250, verbose_name='Nazwa faktury'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_netto',
            field=models.FloatField(verbose_name='Kwota netto'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_nr',
            field=models.CharField(max_length=250, verbose_name='Numer faktur'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_place',
            field=models.CharField(choices=[('Żagań', 'Żagań'), ('Krasiczyn', 'Krasiczyn'), ('Kielce', 'Kielce'), ('Żory', 'Żory'), ('Nie dotyczy', 'Nie dotyczy')], default='Nie dotyczy', max_length=20, verbose_name='Miejsce którego dotyczy'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_vat',
            field=models.FloatField(verbose_name='Vat'),
        ),
    ]
