# Generated by Django 2.2.9 on 2020-01-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date_of_issue', models.DateField()),
                ('invoice_nr', models.CharField(max_length=250)),
                ('invoice_name', models.CharField(max_length=250)),
                ('invoice_netto', models.FloatField()),
                ('invoice_vat', models.FloatField()),
                ('invoice_brutto', models.FloatField(default=100)),
                ('invoice_file', models.FileField(upload_to='')),
            ],
        ),
    ]
